# Generated by Django 4.2.6 on 2025-07-07 19:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inward",
            fields=[
                (
                    "inward_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_nmbr", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("dc_no", models.CharField(max_length=100)),
                ("lr_no", models.CharField(max_length=100)),
                ("vehicle_nmbr", models.CharField(max_length=50)),
                ("received_by", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "material_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("material_name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Outward",
            fields=[
                (
                    "outward_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("indent_no", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("vehicle_no", models.CharField(max_length=50)),
                ("issued_by", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubContractor",
            fields=[
                (
                    "sub_contractor_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sub_contractor_name", models.CharField(max_length=100)),
                ("sub_contractor_licence_no", models.CharField(max_length=50)),
                ("division", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "supplier_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier_name", models.CharField(max_length=100)),
                ("supplier_address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="inventory.material",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubContractorStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.material",
                    ),
                ),
                (
                    "sub_contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.subcontractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutwardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.material",
                    ),
                ),
                (
                    "outward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.outward",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="outward",
            name="sub_contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.subcontractor",
            ),
        ),
        migrations.CreateModel(
            name="InwardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_per_challan",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("actual", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rejected", models.DecimalField(decimal_places=2, max_digits=10)),
                ("accepted", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remarks", models.TextField(blank=True)),
                (
                    "inward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inward",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.material",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inward",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.supplier"
            ),
        ),
    ]
