# Generated by Django 4.2.6 on 2025-07-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontractorstock",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
