# Generated by Django 4.2.6 on 2025-12-17 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_subcontractorstock_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indent",
            fields=[
                (
                    "indent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("indent_no", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StoreStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "wo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wo_number", models.CharField(max_length=100)),
                ("bescom_office", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name="inwarditem",
            old_name="accepted",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="material",
            old_name="material_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="outward",
            old_name="sub_contractor",
            new_name="subcontractor",
        ),
        migrations.RenameField(
            model_name="subcontractor",
            old_name="sub_contractor_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="subcontractor",
            old_name="sub_contractor_id",
            new_name="subcontractor_id",
        ),
        migrations.RenameField(
            model_name="subcontractorstock",
            old_name="sub_contractor",
            new_name="subcontractor",
        ),
        migrations.RemoveField(
            model_name="inward",
            name="dc_no",
        ),
        migrations.RemoveField(
            model_name="inward",
            name="invoice_nmbr",
        ),
        migrations.RemoveField(
            model_name="inward",
            name="lr_no",
        ),
        migrations.RemoveField(
            model_name="inward",
            name="received_by",
        ),
        migrations.RemoveField(
            model_name="inward",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="inward",
            name="vehicle_nmbr",
        ),
        migrations.RemoveField(
            model_name="inwarditem",
            name="actual",
        ),
        migrations.RemoveField(
            model_name="inwarditem",
            name="as_per_challan",
        ),
        migrations.RemoveField(
            model_name="inwarditem",
            name="rejected",
        ),
        migrations.RemoveField(
            model_name="inwarditem",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="outward",
            name="indent_no",
        ),
        migrations.RemoveField(
            model_name="outward",
            name="issued_by",
        ),
        migrations.RemoveField(
            model_name="outward",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="outward",
            name="vehicle_no",
        ),
        migrations.RemoveField(
            model_name="subcontractor",
            name="division",
        ),
        migrations.RemoveField(
            model_name="subcontractor",
            name="sub_contractor_licence_no",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="supplier_address",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="supplier_name",
        ),
        migrations.AddField(
            model_name="subcontractor",
            name="contact_info",
            field=models.CharField(default="000", max_length=200),
        ),
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="name",
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subcontractorstock",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="subcontractorstock",
            unique_together={("subcontractor", "material")},
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.AddField(
            model_name="workordermaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.material"
            ),
        ),
        migrations.AddField(
            model_name="workordermaterial",
            name="wo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="inventory.workorder",
            ),
        ),
        migrations.AddField(
            model_name="storestock",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.material"
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="subcontractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.subcontractor",
            ),
        ),
        migrations.AddField(
            model_name="indent",
            name="wo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.workorder"
            ),
        ),
        migrations.AddField(
            model_name="outward",
            name="indent",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.indent",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="storestock",
            unique_together={("material",)},
        ),
    ]
