# Generated by Django 6.0.1 on 2026-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_indent_storestock_workorder_workordermaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inward',
            name='inward_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
