# Generated by Django 6.0.1 on 2026-01-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inward_inward_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='inward_no',
        ),
    ]
