# Generated by Django 6.0.2 on 2026-03-06 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inward_dc_no_inward_lr_no_inward_vehicle_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indent',
            name='date',
            field=models.DateField(default='2026-03-06'),
        ),
        migrations.AddField(
            model_name='indent',
            name='status',
            field=models.CharField(default='Todo', max_length=50),
        ),
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.indent')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
            options={
                'unique_together': {('indent', 'material')},
            },
        ),
    ]
