# Generated by Django 6.0.1 on 2026-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inward_dc_no_inward_lr_no_inward_vehicle_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indent',
            name='wo',
        ),
        migrations.AddField(
            model_name='indent',
            name='wo',
            field=models.ManyToManyField(to='inventory.workorder'),
        ),
    ]
