# Generated by Django 6.0.1 on 2026-04-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_indent_date_indent_status_indentitem'),
        ('inventory', '0007_remove_indent_wo_indent_wo'),
    ]

    operations = [
    ]
