# Generated by Django 6.0.1 on 2026-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_merge_20260404_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
