# Generated by Django 6.0.1 on 2026-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_workordermaterial_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermaterial',
            name='date',
        ),
        migrations.AddField(
            model_name='workorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
